### ISSUE TITLE
Problemas ao rodar db:seed

### ISSUE THREAD

**Issue by Leocardoso94** [Gestao-Paroquial/back-end#15]
@ocimarpsouza tentei rodar o comando de seed das tabelas, mas está com erro, segue a descrição do erro

In Connection.php line 664:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel`.`comunida
  des`, CONSTRAINT `comunidades_classe_telefone_id_foreign` FOREIGN KEY (`classe_telefone_id`) REFERENCES `classe_telefones` (`id`) ON DELETE
   CASCADE) (SQL: insert into `comunidades` (`classe_telefone_id`, `nome`, `email`, `cnpj`, `endereco`, `nro`, `compl`, `bairro`, `cidade`, `
  uf`, `cep`, `updated_at`, `created_at`) values (1, comunidade teste, dovie02@example.org, 111111111000110, rua são paulo, 100, sala 1, cent
  ro, São paulo, SP, 00000000, 2018-03-26 11:24:16, 2018-03-26 11:24:16))

In Connection.php line 458:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel`.`comunida
  des`, CONSTRAINT `comunidades_classe_telefone_id_foreign` FOREIGN KEY (`classe_telefone_id`) REFERENCES `classe_telefones` (`id`) ON DELETE
   CASCADE)

**Comment by ocimarpsouza** [comment]
este erro é pq precisa rodar um script antes no banco, após o comando php artisan migrate, segue o script abaixo.

Antes de executar rodar este comando php artisan migrate:refresh

insert into classe_telefones (descricao) values ('Comunidade');
insert into classe_telefones (descricao) values ('pastorais');
insert into classe_telefones (descricao) values ('membros');
insert into classe_telefones (descricao) values ('casamentos');
insert into classe_telefones (descricao) values ('batismos');
insert into tipo_dependentes (descricao) values ('Conjuge');
insert into tipo_dependentes (descricao) values ('Filho');
insert into tipo_dependentes (descricao) values ('Filha');
insert into tipo_dependentes (descricao) values ('Pai');
insert into tipo_dependentes (descricao) values ('Mãe');
insert into tipo_dependentes (descricao) values ('Avô');
insert into tipo_dependentes (descricao) values ('Avó');
insert into tipo_dependentes (descricao) values ('Outro');
insert into tipo_doacoes (descricao) values ('Oferta');
insert into tipo_doacoes (descricao) values ('Arrecadação em festa');
insert into tipo_eventos (descricao) values ('Festa');
insert into tipo_eventos (descricao) values ('Batismo');
insert into tipo_eventos (descricao) values ('Casamento');
insert into tipo_eventos (descricao) values ('Quermesse');
insert into tipo_lancamentos (descricao) values ('Crédito');
insert into tipo_lancamentos (descricao) values ('Débito');
insert into tipo_membros (descricao) values ('Visitante');
insert into tipo_membros (descricao) values ('Membro');
insert into tipo_membros (descricao) values ('Membro e dizimista');
insert into tipo_pagamentos (descricao) values ('Dinheiro');
insert into tipo_pagamentos (descricao) values ('Cartão débito');
insert into tipo_pagamentos (descricao) values ('Cartão crédito');
insert into tipo_pagamentos (descricao) values ('Cheque');


após rodar o script no banco, rodar o db:seed
